# Generated by Django 5.0.7 on 2024-10-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
