# Generated by Django 5.0.7 on 2024-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor_date_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Process', 'Processing'), ('Shipped', 'PShipped')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'In_review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★✩✩✩'), (4, '★★★★✩'), (5, '★★★★★'), (3, '★★★✩✩'), (1, '★✩✩✩✩')], default=None),
        ),
    ]
