# Generated by Django 5.0.7 on 2024-10-17 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★✩✩✩'), (1, '★✩✩✩✩'), (5, '★★★★★'), (3, '★★★✩✩'), (4, '★★★★✩')], default=None),
        ),
        migrations.CreateModel(
            name='CartOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=200)),
                ('product_status', models.CharField(choices=[('delivered', 'Delivered'), ('Process', 'Processing'), ('Shipped', 'PShipped')], default='processing', max_length=30)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=299)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Cart Order Items',
            },
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
    ]
