# Generated by Django 5.0.7 on 2024-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('Shipped', 'PShipped'), ('Processing', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(choices=[('Shipped', 'PShipped'), ('Processing', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★✩✩✩'), (5, '★★★★★'), (4, '★★★★✩'), (3, '★★★✩✩'), (1, '★✩✩✩✩')], default=None),
        ),
    ]
