# Generated by Django 5.0.7 on 2024-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_address_mobile_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Shipped', 'PShipped'), ('Processing', 'Processing')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Shipped', 'PShipped'), ('Processing', 'Processing')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★✩✩✩'), (5, '★★★★★'), (3, '★★★✩✩'), (1, '★✩✩✩✩'), (4, '★★★★✩')], default=None),
        ),
    ]
